export const projectsData = [
  {
    id: 2,
    title: "Tjekmate",
    subtitle: "a chess app",
    imagePath: "./tjekmate.jpg",
    altText: "tjekmate app",
    description: [
      "This was my exam project for a full-stack NodeJS course. I used a third party library containing the chess logic, and then built the app around it.",
      "Most of the course was spent on NodeJS, Express and REST APIs. I then added socket logic with SocketIO for real-time updates when the players move their pieces, as well as a database through MongoDB to store data.",
      "The addition of sockets definitely made the project a lot more difficult, but in the end I'm glad I got to try my hand as it's not an uncommon thing to utilise these days.",
    ],
    tags: ["NodeJS", "Express", "MongoDB", "Sockets", "HTML", "CSS", "REST API"],
    urlName: "tjekmate",
    liveSiteUrl: "https://tjekmate.herokuapp.com",
    githubUrl: "https://github.com/JoakimGit/checkmate",
  },
  {
    id: 1,
    title: "Issue Hunter",
    subtitle: "an issue tracker",
    imagePath: "./issue-hunter.jpg",
    altText: "issue hunter app",
    description: [
      "My final exam for the degree was this project. It involved not only building the program, but also the planning, analysis and modelling required to complete it.",
      "I opted for a MEAN stack, as I already had experience with all the technologies involved, except for TailwindCSS which I got to try for the first time, and I learned that I quite like it.",
      "An issue tracker is a commonly used piece of software, so I thought it would be a good project to complete as it has real world value, albeit not so much my system as it can't quite compete with the existing solutions on the market.",
      "Even though I had used MongoDB a few times before this project, this was the first time I got to use Mongoose as an ORM, which I really liked.",
    ],
    tags: ["NodeJS", "Express", "MongoDB", "Angular", "TypeScript", "HTML", "TailwindCSS", "REST API"],
    urlName: "issue-hunter",
    liveSiteUrl: "https://issue-hunter.herokuapp.com/",
    githubUrl: "https://github.com/JoakimGit/IssueHunter",
  },
];
